name: ci

on: [push, pull_request]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: .
        name: project
    
    
    
    